### ISSUE TITLE
Broken in Openfire 4.7.0

### ISSUE THREAD

**Issue by Fishbowler** [igniterealtime/openfire-rawpropertyeditor-plugin#6]
When visiting a room and viewing it's properties, an error is displayed on `groupchat-propertiesplugin.jsp`

```
java.lang.IncompatibleClassChangeError: Found class org.jivesoftware.openfire.muc.MUCRoom, but interface was expected
	at org.jivesoftware.openfire.plugin.RawPropertyEditorPlugin.getAndCheckGroupChat(RawPropertyEditorPlugin.java:129)
	at org.jivesoftware.openfire.plugin.RawPropertyEditorPlugin.getGroupChatProperties(RawPropertyEditorPlugin.java:140)
	at org.jivesoftware.openfire.plugin.rawpropertyeditor.groupchat_002dpropertiesplugin_jsp._jspService(groupchat_002dpropertiesplugin_jsp.java:165)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
       <snip>
```

MUC has been reworked in 4.7.0, but likely not a massive refactor here to get this working again.

**Comment by Fishbowler** [comment]
Having had a little play I _think_ this is just resolved by setting the Parent version in the POM to 4.7.0 (and the equivalent minServerVersion on release)

**Comment by Fishbowler** [comment]
But there might be other instances in JSP that I've not accounted for
